#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License" #mandatory https://choosealicense.com/

 
[[mods]] #mandatory
modId="phlaxmod" #mandatory
version="0.001" #mandatory
displayName="PHLAX MAGIX" #mandatory
credits="Me of course. Also I owe my life to jdawg3636." #optional
authors="GunMetalBlack" #optional
description='''
It's a magic + tech mod.
I have no idea what I'm doing 
''' #mandatory